// Generated by scripts/prepare-logos.mjs — do not edit by hand.
// width/height are the trimmed artwork (incl. safety margin) in source pixels;
// components scale them to a display height while keeping the exact ratio.

import parentWebp2x from "./parent@2x.webp";
import parentWebp3x from "./parent@3x.webp";
import parentPng from "./parent@2x.png";
import merlinWebp2x from "./merlin@2x.webp";
import merlinWebp3x from "./merlin@3x.webp";
import merlinPng from "./merlin@2x.png";
import medicalAdvisoryWebp2x from "./medicalAdvisory@2x.webp";
import medicalAdvisoryWebp3x from "./medicalAdvisory@3x.webp";
import medicalAdvisoryPng from "./medicalAdvisory@2x.png";
import civilServicesWebp2x from "./civilServices@2x.webp";
import civilServicesWebp3x from "./civilServices@3x.webp";
import civilServicesPng from "./civilServices@2x.png";

export const logos = {
  parent: { webp2x: parentWebp2x, webp3x: parentWebp3x, png: parentPng, width: 4106, height: 1044 },
  merlin: { webp2x: merlinWebp2x, webp3x: merlinWebp3x, png: merlinPng, width: 2636, height: 846 },
  medicalAdvisory: { webp2x: medicalAdvisoryWebp2x, webp3x: medicalAdvisoryWebp3x, png: medicalAdvisoryPng, width: 1102, height: 298 },
  civilServices: { webp2x: civilServicesWebp2x, webp3x: civilServicesWebp3x, png: civilServicesPng, width: 1101, height: 297 },
} as const;

export type LogoKey = keyof typeof logos;
